name: lorem_ipsum_generator
description: lorem_ipsum_generator uses a straightforward API and customizable settings to generate random "lorem ipsum" text.
version: 0.0.3
homepage: https://github.com/SamanKC/lorem_ipsum_generator

environment:
  sdk: ">=2.19.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
